// Файл генерируется плагином svg-sprite. Не редактировать вручную.
export type IconName =
  | 'alert-circle'
  | 'arrow-left'
  | 'book'
  | 'calendar'
  | 'chart'
  | 'check'
  | 'chevron-left'
  | 'clock'
  | 'download'
  | 'eye-off'
  | 'eye'
  | 'file'
  | 'home'
  | 'lock'
  | 'logout'
  | 'mail'
  | 'plus'
  | 'search'
  | 'trash'
  | 'upload'
  | 'user'
  | 'x'
